name: Laravel CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Set up job
        run: echo "Starting automated deployment on local server..."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest code and restart Docker
        run: |
          git pull origin master
          docker-compose down
          docker-compose up -d --build

      - name: Complete job
        run: echo "Deployment completed successfully!"