name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: CDPTW

    steps:
      - name: Lay code
        uses: actions/checkout@v4

      - name: Cai PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, sqlite, dom, fileinfo
          coverage: none

      - name: Cai thu vien Composer
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Key
        run: php artisan key:generate

      - name: Chay Laravel test
        run: php artisan test